sudo: required
services:
  - docker
language: go
notifications:
  email: true
go:
  - 1.9
go_import_path: k8s.io/ingress
jobs:
  include:
    - stage: Build
      script:
        - make
    - stage: Test
      script:
        - make test
